/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	scheme "github.com/OpenCIDN/cidn/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BearersGetter has a method to return a BearerInterface.
// A group's client should implement this interface.
type BearersGetter interface {
	Bearers() BearerInterface
}

// BearerInterface has methods to work with Bearer resources.
type BearerInterface interface {
	Create(ctx context.Context, bearer *taskv1alpha1.Bearer, opts v1.CreateOptions) (*taskv1alpha1.Bearer, error)
	Update(ctx context.Context, bearer *taskv1alpha1.Bearer, opts v1.UpdateOptions) (*taskv1alpha1.Bearer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bearer *taskv1alpha1.Bearer, opts v1.UpdateOptions) (*taskv1alpha1.Bearer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*taskv1alpha1.Bearer, error)
	List(ctx context.Context, opts v1.ListOptions) (*taskv1alpha1.BearerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *taskv1alpha1.Bearer, err error)
	BearerExpansion
}

// bearers implements BearerInterface
type bearers struct {
	*gentype.ClientWithList[*taskv1alpha1.Bearer, *taskv1alpha1.BearerList]
}

// newBearers returns a Bearers
func newBearers(c *TaskV1alpha1Client) *bearers {
	return &bearers{
		gentype.NewClientWithList[*taskv1alpha1.Bearer, *taskv1alpha1.BearerList](
			"bearers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *taskv1alpha1.Bearer { return &taskv1alpha1.Bearer{} },
			func() *taskv1alpha1.BearerList { return &taskv1alpha1.BearerList{} },
		),
	}
}
