/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	scheme "github.com/OpenCIDN/cidn/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MultipartsGetter has a method to return a MultipartInterface.
// A group's client should implement this interface.
type MultipartsGetter interface {
	Multiparts() MultipartInterface
}

// MultipartInterface has methods to work with Multipart resources.
type MultipartInterface interface {
	Create(ctx context.Context, multipart *taskv1alpha1.Multipart, opts v1.CreateOptions) (*taskv1alpha1.Multipart, error)
	Update(ctx context.Context, multipart *taskv1alpha1.Multipart, opts v1.UpdateOptions) (*taskv1alpha1.Multipart, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*taskv1alpha1.Multipart, error)
	List(ctx context.Context, opts v1.ListOptions) (*taskv1alpha1.MultipartList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *taskv1alpha1.Multipart, err error)
	MultipartExpansion
}

// multiparts implements MultipartInterface
type multiparts struct {
	*gentype.ClientWithList[*taskv1alpha1.Multipart, *taskv1alpha1.MultipartList]
}

// newMultiparts returns a Multiparts
func newMultiparts(c *TaskV1alpha1Client) *multiparts {
	return &multiparts{
		gentype.NewClientWithList[*taskv1alpha1.Multipart, *taskv1alpha1.MultipartList](
			"multiparts",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *taskv1alpha1.Multipart { return &taskv1alpha1.Multipart{} },
			func() *taskv1alpha1.MultipartList { return &taskv1alpha1.MultipartList{} },
		),
	}
}
