/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	scheme "github.com/OpenCIDN/cidn/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SyncsGetter has a method to return a SyncInterface.
// A group's client should implement this interface.
type SyncsGetter interface {
	Syncs() SyncInterface
}

// SyncInterface has methods to work with Sync resources.
type SyncInterface interface {
	Create(ctx context.Context, sync *taskv1alpha1.Sync, opts v1.CreateOptions) (*taskv1alpha1.Sync, error)
	Update(ctx context.Context, sync *taskv1alpha1.Sync, opts v1.UpdateOptions) (*taskv1alpha1.Sync, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*taskv1alpha1.Sync, error)
	List(ctx context.Context, opts v1.ListOptions) (*taskv1alpha1.SyncList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *taskv1alpha1.Sync, err error)
	SyncExpansion
}

// syncs implements SyncInterface
type syncs struct {
	*gentype.ClientWithList[*taskv1alpha1.Sync, *taskv1alpha1.SyncList]
}

// newSyncs returns a Syncs
func newSyncs(c *TaskV1alpha1Client) *syncs {
	return &syncs{
		gentype.NewClientWithList[*taskv1alpha1.Sync, *taskv1alpha1.SyncList](
			"syncs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *taskv1alpha1.Sync { return &taskv1alpha1.Sync{} },
			func() *taskv1alpha1.SyncList { return &taskv1alpha1.SyncList{} },
		),
	}
}
