services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: unless-stopped


  minio:
    image: m.daocloud.io/quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    entrypoint:
    - sh
    command:
    - -c
    - |-
      (
        while true; do
            mc alias set local http://127.0.0.1:9000 minioadmin minioadmin && break
            sleep 2
        done

        mc mb local/myminio
      ) &
      
      /usr/bin/docker-entrypoint.sh server /data --console-address ":9001"
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin


  etcd:
    image: m.daocloud.io/quay.io/coreos/etcd:v3.6.1
    command: 
      - /usr/local/bin/etcd
      - --name=node0
      - --auto-compaction-retention=1
      - --quota-backend-bytes=8589934592
      - --data-dir=/var/lib/etcd
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node0=http://0.0.0.0:2380
    ports:
      - "2379:2379"
    restart: unless-stopped

  apiserver:
    build:
      context: .
      dockerfile: images/apiserver/Dockerfile
    ports:
    - "6443:6443"
    depends_on:
    - etcd
    restart: unless-stopped
    command:
    - --etcd-servers=http://etcd:2379

  controller-manager:
    build:
      context: .
      dockerfile: images/controller-manager/Dockerfile
    depends_on:
    - apiserver
    - minio
    restart: unless-stopped
    command:
    - --kubeconfig=/kubeconfig.local.yaml
    - --master=https://apiserver:6443
    - --storage-url=minio://minioadmin:minioadmin@myminio.us-east-1?forcepathstyle=true&secure=false&chunksize=104857600&regionendpoint=http://minio:9000
    volumes:
    - ./kubeconfig.local.yaml:/kubeconfig.local.yaml:ro

  runner:
    build:
      context: .
      dockerfile: images/runner/Dockerfile
    depends_on:
    - apiserver
    - minio
    - nginx
    restart: unless-stopped
    command:
    - --kubeconfig=/kubeconfig.local.yaml
    - --master=https://apiserver:6443
    volumes:
    - ./kubeconfig.local.yaml:/kubeconfig.local.yaml:ro
