services:
  minio:
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 3s
    image: m.daocloud.io/quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    entrypoint:
    - sh
    command:
    - -c
    - |-
      (
        while true; do
            mc alias set local http://127.0.0.1:9000 minioadmin minioadmin && break
            sleep 2
        done

        mc mb local/myminio
      ) &
      /usr/bin/docker-entrypoint.sh server /data/$${HOSTNAME}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    deploy:
      replicas: 2
    networks:
      controller-tier: {}
      runner-tier: {}
    volumes:
    - cache-data:/data
  etcd:
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 3s
    image: m.daocloud.io/quay.io/coreos/etcd:v3.6.1
    command:
    - /usr/local/bin/etcd
    - --name=node0
    - --auto-compaction-retention=1
    - --quota-backend-bytes=8589934592
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=http://0.0.0.0:2380
    - --listen-peer-urls=http://0.0.0.0:2380
    - --advertise-client-urls=http://0.0.0.0:2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --initial-cluster=node0=http://0.0.0.0:2380
    networks:
      controller-tier: {}
    volumes:
    - db-data:/var/lib/etcd
  apiserver:
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 3s
    build:
      context: .
      dockerfile: images/apiserver/Dockerfile
    depends_on:
      etcd:
        condition: service_started
        restart: true
    command:
    - --etcd-servers=http://etcd:2379
    - --user=admin:admin-pwd,cidn:controller-manager
    - --user=runner:runner-pwd,cidn:runner
    - --user=viewer:viewer-pwd,cidn:viewer
    ports:
    - "6443:6443"
    networks:
      controller-tier: {}
      runner-tier: {}
  controller-manager:
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 10s
    build:
      context: .
      dockerfile: images/controller-manager/Dockerfile
    depends_on:
      apiserver:
        condition: service_started
        restart: true
    command:
    - --master=https://admin:admin-pwd@apiserver:6443
    - --insecure-skip-tls-verify
    - --storage-url=minio-1://minioadmin:minioadmin@myminio.us-east-1?forcepathstyle=true&secure=false&chunksize=104857600&regionendpoint=http://cidn-minio-1:9000
    - --storage-url=minio-2://minioadmin:minioadmin@myminio.us-east-1?forcepathstyle=true&secure=false&chunksize=104857600&regionendpoint=http://cidn-minio-2:9000
    deploy:
      replicas: 2
    networks:
      controller-tier: {}
  runner:
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 10s
    build:
      context: .
      dockerfile: images/runner/Dockerfile
    depends_on:
      apiserver:
        condition: service_started
        restart: true
      minio:
        condition: service_started
        restart: true
      nginx-test:
        condition: service_started
        restart: true
    command:
    - --master=https://runner:runner-pwd@apiserver:6443
    - --insecure-skip-tls-verify
    deploy:
      replicas: 8
    networks:
      runner-tier: {}
  webui:
    restart: unless-stopped
    build:
      context: .
      dockerfile: images/webui/Dockerfile
    depends_on:
      apiserver:
        condition: service_started
        restart: true
    command:
    - --master=https://viewer:viewer-pwd@apiserver:6443
    - --insecure-skip-tls-verify
    - --port=8080
    ports:
    - "8080:8080"
    networks:
      controller-tier: {}
  nginx-test:
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 3s
    image: m.daocloud.io/docker.io/nginx:alpine
    volumes:
    - ./tests/testdata:/usr/share/nginx/html:ro
    configs:
    - source: nginx-test-config
      target: /etc/nginx/conf.d/default.conf
      mode: 0440
    deploy:
      replicas: 2
    networks:
      runner-tier: {}
configs:
  nginx-test-config:
    content: |-
      server {
        listen 80;
        location / {
          if ($$request_id ~* "[1]$$") {
            return 500;
          }
          if ($$request_id ~* "[2]$$") {
            return 444;
          }
          limit_rate 10m;
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
      }
networks:
  controller-tier: {}
  runner-tier: {}
volumes:
  cache-data: {}
  db-data: {}
