/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BearerLister helps list Bearers.
// All objects returned here must be treated as read-only.
type BearerLister interface {
	// List lists all Bearers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*taskv1alpha1.Bearer, err error)
	// Get retrieves the Bearer from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*taskv1alpha1.Bearer, error)
	BearerListerExpansion
}

// bearerLister implements the BearerLister interface.
type bearerLister struct {
	listers.ResourceIndexer[*taskv1alpha1.Bearer]
}

// NewBearerLister returns a new BearerLister.
func NewBearerLister(indexer cache.Indexer) BearerLister {
	return &bearerLister{listers.New[*taskv1alpha1.Bearer](indexer, taskv1alpha1.Resource("bearer"))}
}
