/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MultipartLister helps list Multiparts.
// All objects returned here must be treated as read-only.
type MultipartLister interface {
	// List lists all Multiparts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*taskv1alpha1.Multipart, err error)
	// Get retrieves the Multipart from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*taskv1alpha1.Multipart, error)
	MultipartListerExpansion
}

// multipartLister implements the MultipartLister interface.
type multipartLister struct {
	listers.ResourceIndexer[*taskv1alpha1.Multipart]
}

// NewMultipartLister returns a new MultipartLister.
func NewMultipartLister(indexer cache.Indexer) MultipartLister {
	return &multipartLister{listers.New[*taskv1alpha1.Multipart](indexer, taskv1alpha1.Resource("multipart"))}
}
