/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apistaskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	versioned "github.com/OpenCIDN/cidn/pkg/clientset/versioned"
	internalinterfaces "github.com/OpenCIDN/cidn/pkg/informers/externalversions/internalinterfaces"
	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/listers/task/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BearerInformer provides access to a shared informer and lister for
// Bearers.
type BearerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() taskv1alpha1.BearerLister
}

type bearerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBearerInformer constructs a new informer for Bearer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBearerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBearerInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBearerInformer constructs a new informer for Bearer type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBearerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Bearers().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Bearers().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Bearers().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Bearers().Watch(ctx, options)
			},
		},
		&apistaskv1alpha1.Bearer{},
		resyncPeriod,
		indexers,
	)
}

func (f *bearerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBearerInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bearerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apistaskv1alpha1.Bearer{}, f.defaultInformer)
}

func (f *bearerInformer) Lister() taskv1alpha1.BearerLister {
	return taskv1alpha1.NewBearerLister(f.Informer().GetIndexer())
}
