/*
Copyright The OpenCIDN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apistaskv1alpha1 "github.com/OpenCIDN/cidn/pkg/apis/task/v1alpha1"
	versioned "github.com/OpenCIDN/cidn/pkg/clientset/versioned"
	internalinterfaces "github.com/OpenCIDN/cidn/pkg/informers/externalversions/internalinterfaces"
	taskv1alpha1 "github.com/OpenCIDN/cidn/pkg/listers/task/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MultipartInformer provides access to a shared informer and lister for
// Multiparts.
type MultipartInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() taskv1alpha1.MultipartLister
}

type multipartInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMultipartInformer constructs a new informer for Multipart type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMultipartInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMultipartInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMultipartInformer constructs a new informer for Multipart type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMultipartInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Multiparts().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Multiparts().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Multiparts().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskV1alpha1().Multiparts().Watch(ctx, options)
			},
		},
		&apistaskv1alpha1.Multipart{},
		resyncPeriod,
		indexers,
	)
}

func (f *multipartInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMultipartInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *multipartInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apistaskv1alpha1.Multipart{}, f.defaultInformer)
}

func (f *multipartInformer) Lister() taskv1alpha1.MultipartLister {
	return taskv1alpha1.NewMultipartLister(f.Informer().GetIndexer())
}
